### ISSUE TITLE
onMove function

### ISSUE THREAD

**Issue by gabrilator** [react-chess/chessground#12]
Hey! Great job with the library, enjoying it so far! 

I wonder if there's an implementation of onMove to receive the from and to after a user moves.

Thanks a lot!
Gabriel

**Comment by yarrichar** [comment]
Yes, you need to pass it in through the config property.

```        
        <Chessground config={{
            events: {
                move: onMove
            }
        }} />
```

Where onMove has signature: `move?: (orig: cg.Key, dest: cg.Key, capturedPiece?: cg.Piece) => void;`

**Comment by richardxhong** [comment]
> Yes, you need to pass it in through the config property.
> 
> ```
>         <Chessground config={{
>             events: {
>                 move: onMove
>             }
>         }} />
> ```
> 
> Where onMove has signature: `move?: (orig: cg.Key, dest: cg.Key, capturedPiece?: cg.Piece) => void;`

awesome response, thanks for resolving!
