### ISSUE TITLE
How do I make valid moves?

### ISSUE THREAD

**Issue by agawrylak** [react-chess/chessground#4]
How to make a move function that works with chess.js?

**Comment by huydhoang** [comment]
> How to make a move function that works with chess.js?

This is not a full solution but you can start from here.
Visit [chess.js](https://github.com/jhlywa/chess.js) and create a `Chess` object, then bind the `Chess.fen` to Chessground like this:
```ts
<Chessground
  config={{
    fen: Chess.fen,
  }}
/>
```
