### ISSUE TITLE
Compile issues using vanilla CRA project

### ISSUE THREAD

**Issue by matt-d-webb** [react-chess/chessground#5]
Hey 👋🏼 

When doing a basic `create-react-app` project using this package, I get the following compile errors.

#### Steps to recreate:

1. boiler plater CRA
```
npx create-react-app chessboard-test
```

2. add `chessground` react dependency

```
yarn add @react-chess/chessground
```

3. add component to root `src/App.js`
```js
import Chessground from '@react-chess/chessground';
function App() {
  return (
    <div>
      <Chessground />
    </div>
  );
}
export default App;
```

4. start project
```
yarn start
```

#### Environment:
- Windows 10 / Mac OS Catalina
- node: `v14.18.2`
- npm: `v6.14.15`
- react: `^16.8.0` & tried `^17.0.3`
- react-dom: `^16.8.0` & tried `^17.0.3`

#### Error Output (Windows)
![image](https://user-images.githubusercontent.com/36933715/148025576-aa23c4ea-f9ca-4ed9-ad49-e3811f9b66c9.png)

### Error Output (Mac OS)
<img width="866" alt="Screenshot 2022-01-04 at 07 56 52" src="https://user-images.githubusercontent.com/36933715/148027527-f62144ea-8062-4c1a-a8ea-b1fe41e1351f.png">

💭 _Wonder if this is an issue specifically with the parent project `chessground` and adding `resolve: { fullySpecified: false }` is required in their webpack build._

**Comment by richardxhong** [comment]
thank you so much for this, I will do some investigating!

**Comment by matt-d-webb** [comment]
Nice work, thanks dude! 😎

**Comment by richardxhong** [comment]
@matt-d-webb actually not sure if it's 100% fixed, I ran out of travis-CI credits so I haven't published a new package version yet :rofl:

**Comment by richardxhong** [comment]
trying to setup some github actions to take over

**Comment by richardxhong** [comment]
you're right, this looks like an issue with the parent project chessground, going to publish a new version of this locked chessground 7.1 and work on getting an up to date version later
