### ISSUE TITLE
Chessboard doesn't seem to be affected by styling.

### ISSUE THREAD

**Issue by d-luca727** [react-chess/chessground#9]
I have this code:
```
                  <div className="board">
                    <Chessground
                      width={boardWidth}
                      height={boardWidth}
                      config={config}
                    />
                  </div>

.board {
  margin: 0 auto;
  text-align: center;
  position: relative;
}
```
(e.g. https://imgur.com/qfqmrvp)
Chessground doesn't change according to my css, how do I fix? I've built a lot of chess projects just to play around with this wrapper and this is the only thing I can't figure out.

**Comment by richardxhong** [comment]
```jsx
<div className="container"> 
  <div className="board">
    <Chessground
       config={config} 
       contained />
  </div>
</div>
```

I recommend something like this instead, the `board` class needs to have width and height property set, and you can style it however you like after

**Comment by d-luca727** [comment]
It worked like a charm, thanks for helping out!
